postgresql:
  image: postgres:10.7-alpine
  container_name: timesup-local-pgsql
  ports:
    - "5432:5432"
  restart: always
  environment:
    POSTGRES_USER: "dbuser"
    POSTGRES_PASSWORD: "secretpassword"
    POSTGRES_DB: "mydb"
  volumes:
    - postgres:/var/lib/postgresql/data
